### ISSUE TITLE
新版解析微信消息是不是有问题？

### ISSUE THREAD

**Issue by itaotao** [antgan/wx-tools#5]
`// 微信服务器推送过来的是XML格式。
     WxXmlMessage wx=XStreamTransformer.fromXml(WxXmlMessage.class,request.getInputStream());

 System.out.println(wx.getContent());

 Log.info("消息：\n " + wx.toString());`

我打印request.getInputStream()是内容的，你这个 WxXmlMessage wx怎么没有内容？？

**Comment by antgan** [comment]
应该是没问题的。其他同学都在用。

**Comment by itaotao** [comment]
String input = "<xml><ToUserName><![CDATA[gh_d556e752ca65]]></ToUserName>" +
                        "<FromUserName><![CDATA[oq6CPtzsO2D_7HvgqICZtXjXuzwY]]></FromUserName>" +
                        "<CreateTime>1499423160</CreateTime>" +
                        "<MsgType><![CDATA[text]]></MsgType>" +
                        "<Content><![CDATA[北京]]></Content>" +
                        "<MsgId>6439973435492463981</MsgId>" +
                        "</xml>";
你带进去试试 看看可以不可以 如果可以 那你觉得我这可能是什么问题 也没报什么异常

**Comment by antgan** [comment]
建议你别自定义微信服务器消息，直接用测试号去测试比较好。搭建好自己的服务器并校验通过后，任何公众号的操作（消息或者事件）都算消息发送给你的服务器的。

**Comment by itaotao** [comment]
这个就是微信服务器下发的 我打印出来的

**Comment by antgan** [comment]
建议你+一个Q群570937047 ，方便问下大家。大家都没遇到问题哦~
